### ISSUE TITLE
Missing argument 3 for ACFtoWPAPI::addACFDataTerm()

### ISSUE THREAD

**Issue by mcg88** [times/acf-to-wp-api#1]
Hey,

I'm seeing this error popup pretty frequently in my new relic logs. Any idea what may be causing it?

http://screencast.com/t/wkGxkuee75Yz

Running latest version of wordpress.

**Comment by aendra-rininsland** [comment]
@mcgwebdesign We're taking a look at this plugin today, will let you know if we run across it.

**Comment by aendra-rininsland** [comment]
Confirming bug.

**Comment by mcg88** [comment]
Any update on this?

**Comment by chrishutchinson** [comment]
Just a note that this should have been fixed.

@mcgwebdesign could you check your New Relic logs again after pulling the latest version of the plugin?

**Comment by chrishutchinson** [comment]
@mcgwebdesign just checking up if you've been able to take a look at your logs?

**Comment by chrishutchinson** [comment]
I'm closing this as I haven't heard back from you and am not able to reproduce this any more. Please comment or re-open the issue if you are still struggling with it, thanks!
