### ISSUE TITLE
post data back into acf?

### ISSUE THREAD

**Issue by eliezer-rodriguez** [times/acf-to-wp-api#10]
I am building an ios client for the WP API, I am able to read the values from the 'acf' key that comes with the post without any issues. What I am trying to figure out is how to have wordpress save the updates I send back on the custom fields.

Do you have any idea or clue of what filters would allow me  to iterate over the items on the acf array and save their updated values?

**Comment by chrishutchinson** [comment]
Hi there,

You should be able to make a standard POST request to `/wp-json/posts/{id}/meta/{mid}` (authorization is required) with the following data: `data[value]={value}`

Where:
- `{id}` = post ID
- `{mid}` = the meta ID
- `{value}` = the value you wish to set!

I'll close this as it's not an issue with the plugin itself, but feel free to comment on this issue with further related questions, or even better, ask any additional questions in our Gitter chat at https://gitter.im/times/cardkit
