### ISSUE TITLE
ACF Image size

### ISSUE THREAD

**Issue by apsolut** [times/acf-to-wp-api#11]
Can we somehow output Custom Image Size, so its not original (image) url in Output of ACF?

**Comment by chrishutchinson** [comment]
I've just tested this and you are already able to do this via ACF (see attached screenshot of example ACF data in the WP-API json output). This allows you to get a full listing of all available image sizes, under the `sizes` key.

To do so, make sure when you set up your `Image` custom field in ACF, you set the _Return Value_ to `Image Object` (see second screenshot).

Let me know if this solves your problem.

**Example output**
![screen shot 2015-05-11 at 10 11 28](https://cloud.githubusercontent.com/assets/1573022/7561726/30de3b48-f7c6-11e4-9105-b9cb3d958ddf.png)

**ACF Image config**
![screen shot 2015-05-11 at 10 12 46](https://cloud.githubusercontent.com/assets/1573022/7561739/5b6770d2-f7c6-11e4-8f8c-fb5fc9afefa4.png)

**Comment by apsolut** [comment]
Thanks just realized that, easier and safer for future to use (not to edit json output), 
ACF5 is "Image Array"  Thanks @chrishutchinson
