### ISSUE TITLE
Suggestion: Add a CONTRIBUTING.md file or equivalent section to README.md

### ISSUE THREAD

**Issue by aendra-rininsland** [times/acf-to-wp-api#14]
In order to improve the quality of issues in the queue, it might help to have a "CONTRIBUTING.md" file, or a section in the README outlining how to best request help. It seems it would be particularly helpful if issue reporters supply the ACF config when submitting bugs — several recent issues have closed due to the reporter not following up with their config, and while that points to a fault on their end, it makes it hard to investigate whether it's actually an issue with acf2wpapi.

**Comment by chrishutchinson** [comment]
Done - https://github.com/times/acf-to-wp-api/blob/master/CONTRIBUTING.md

Woohoo!
