### ISSUE TITLE
Post object doesn't include ACF fields

### ISSUE THREAD

**Issue by intelligence** [times/acf-to-wp-api#16]
Hey!

Been using this addition for a while, great plugin!
I came across what seems to be a slight problem. If I have a ACF field of the post object variety where I can associate my post with other posts it doesn't seem to include the ACF fields of the included post. Is this expected behavior?

http://www.advancedcustomfields.com/resources/post-object/

![postobject](https://cloud.githubusercontent.com/assets/756582/8376669/02e5941c-1c0a-11e5-8238-dfb63bd7bb0f.png)

**Comment by chrishutchinson** [comment]
Hey @intelligence,

Great spot - this isn't expected behaviour. I've quickly looked into it, and ACF uses a different approach to get post data for `post_object` field types. I'll take a look and see what progress I can make - I'll update here once I know more.

Cheers!

**Comment by intelligence** [comment]
@chrishutchinson Cool, great that you're on this! Any ETA? I realize that you're doing this on your spare time. I'm just curious if you imagine you'll have time to take a look in the near future or if it'll be a while.

Thanks!

**Comment by chrishutchinson** [comment]
Hey,

I've looked into this and there doesn't appear to be any hooks or filters we can use in ACF to add this functionality. Having actually thought about this, I actually do not think it is the best idea, you could potentially get into a situation where there are multiple nested posts – each post having another post associated via ACF. While this is, of course, down the user of the plugin to avoid, I think in most use cases you may not want to get the ACF data for an attached post immediately. If you want to get that data, however, you can just make another request to the API using the ID number of the attached post.

I'm going to close this issue for now, but will take a look at ACF and see if there's a way it could be added in the future, at which point I would add it behind a setting that would be off be default.

Cheers,
Chris
