### ISSUE TITLE
Call to undefined function get_fields()

### ISSUE THREAD

**Issue by lrz-hal** [times/acf-to-wp-api#17]
I installed your plugin in wordpress. unfortunately i get this error 

<br />
<b>Fatal error</b>:  Call to undefined function get_fields() in <b>/var/www/web1205/html/MerseburgerApp/wp-content/plugins/acf-to-wp-api/acf-to-wp-api.php</b> on line <b>57</b><br />

My url is .../wp-json/posts?type=tribe_events

Thanks,

Martin

**Comment by kokarn** [comment]
Have you installed advanced custom fields?

**Comment by lrz-hal** [comment]
Ohh... Thanks for the hint :o)
