### ISSUE TITLE
Pages and custom post types issue with WP-API v2

### ISSUE THREAD

**Issue by chrishutchinson** [times/acf-to-wp-api#21]
I need to do more digging into this, but v2.0-beta4 doesn't seem to handle custom post types very well, so no ACF data comes through there yet.

This doesn't affect users with version 1.x of WP-APi.

**Comment by wkw** [comment]
Is this related to custom post types having to opt-in to the rest api?

`show_in_rest=true`

[https://github.com/WP-API/WP-API/issues/1195](https://github.com/WP-API/WP-API/issues/1195)

**Comment by aderaaij** [comment]
@wkw It doesn't seem so. Enabling the show_in_rest=true enables the custom post type in the REST API but these posts do not include any ACF data. I'll have a look in the plugin code, but any pointers would be greatly appreciated. 

edit: I've had a quick glance and it seems that the register function is only working for the post type `post` and none other. If I add a register function and corresponding `add action` for my custom post type to the plugin, it works like a charm

```
function addACFDataBookV2() {
    register_api_field( 'book',
            'acf',
            array(
                'get_callback'    => array( $this, 'addACFDataPostV2cb' ),
                'update_callback' => null,
                'schema'          => null,
            )
    );
}

add_action( 'rest_api_init', array( $this, 'addACFDataBookV2' ) ); // CPT Books
```

edit2: okay I've temporarily fixed this with the help of the following [blogpost](https://bay-a.co.uk/wordpress-tips/wp-api-v2-tips/). Apparantly you can get all custom post types in an array like this:
`$types = get_post_types(array('public'   => true,'_builtin' => false));`
And so I've added a `register_api_field` function using the `$types` array. Full code

```
    function addACFDataCustomV2() {
        $types = get_post_types(array('public'   => true,'_builtin' => false));
        register_api_field( $types,
            'acf',
            array(
                'get_callback'    => array( $this, 'addACFDataPostV2cb' ),
                'update_callback' => null,
                'schema'          => null,
            )
        );
    }

add_action( 'rest_api_init', array( $this, 'addACFDataCustomV2' ) );
```

I'll fork the plugin and add this. Don't know if it's the correct solution but If wanted I'll do a pr!

**Comment by chrishutchinson** [comment]
Hey @aderaaij,

Thanks for clarifying that. I've actually been planning to add code very similar to the above for the past week or so, and have an almost-completed version running of my machine at the moment.

I've not yet had chance to finish it off and push it up. Happy for you to do a PR as long as everything is commented, indented and structured as per the rest of the repo.

If you don't get chance, I'll aim to get this done by the beginning of next week!

**Comment by richardmax** [comment]
Any joy on this Chris? ie. adding code to core?

**Comment by aderaaij** [comment]
@chrishutchinson that's perfect! I haven't done the PR request yet as I'm just a front-ender faking PHP skills, but I was wondering the follow though: Is there a particular reason why you've written separate functions for getting the page, posts, etc? I'm thinking `$types = get_post_types(array('public'   => true,'_builtin' => true));` would work just as well?

**Comment by adamsoffer** [comment]
Thanks @aderaaij ! Saved me some trouble :+1:

**Comment by chrishutchinson** [comment]
Thanks for all feedback / suggestions everyone - aiming to have this sorted in the plugin this week, will keep you all posted! :+1:

**Comment by nevace** [comment]
Thanks @aderaaij, this was frustrating me all day, thought I was doing something wrong. For now I'm using your version but will change over when the plugin has been updated officially.

**Comment by aderaaij** [comment]
Your welcome guys. thx Chris for the great plugin. I couldn't PHP my way out of a paper bag so without this plugin I would've been nowhere. 

Oh just for the record, there's a PR for this same issue in this repo. It does the same as my changes, albeit a bit different: https://github.com/times/acf-to-wp-api/pull/22

**Comment by chrishutchinson** [comment]
Hey all,

This should now be fixed. I've added a new release in GitHub and pushed the changes to the WordPress Plugin repository!

Please re-open this issue if I missed anything, and thanks again for all your help!

**Comment by nevace** [comment]
Hey @chrishutchinson, thanks for updating, although I just updated the plugin and can't see any acf data anymore.

**Comment by richardmax** [comment]
@chrishutchinson https://github.com/chrishutchinson worked like a charm
for me chris - thanks! r

:::::::::::::::::::::::

Richard Max
07882 259888

**Comment by aderaaij** [comment]
yup, works like a charm dude, thanks. I'll kill my fork! (strange sentence indeed).
