### ISSUE TITLE
Parse error in version 1.3.0

### ISSUE THREAD

**Issue by kmaida** [times/acf-to-wp-api#24]
`Parse error: syntax error, unexpected '[' in acf-to-wp-api/acf-to-wp-api.php on line 403`

Fatal error after updating `acf-to-wp-api` from version `1.2.1` to `1.3.0`; breaks WordPress build until plugin files are removed, or if installing fresh, prevents plugin from being activated. No other plugins updated or changed.

ACF to WP-API 1.3.0
WP-API 1.2.3
WordPress 4.3

Other plugins installed: ACF Pro 5.3.0, Custom Post Type UI 1.1.2

**Comment by chrishutchinson** [comment]
This should be resolved for you now. For reference, the plugin was using the new `[]` notation for arrays, rather than `array()`, which isn't supported in < PHP 5.4.

Hopefully updating the plugin to 1.3.1 will fix this issue for you!

**Comment by kmaida** [comment]
Thanks!! That explains a lot; my PHP is a few years rusty and I'm a JavaScript developer, which would be why I couldn't find anything wrong when I tried to fix it to submit a pull request. ;) Again, thanks for quick response!
