### ISSUE TITLE
Fatal error with get_fields()

### ISSUE THREAD

**Issue by sethvanstaden91** [times/acf-to-wp-api#25]
I have installed this plugin on my wordpress site and im trying to just call what I was before I installed: http://examplesite.com/tna_wp/wp-json/posts?filter[category_name]=lifestyle&filter[posts_per_page]=100

but I am receiving this error
<b>Fatal error</b>:  Call to undefined function get_fields() in <b>/var/www/examplesite.com/tna_wp/wp-content/plugins/acf-to-wp-api/acf-to-wp-api.php</b> on line <b>376</b><br />

is there anymore in terms of setup that I need to do for this?

**Comment by chrishutchinson** [comment]
Have you got ACF installed? `get_fields()` is a function registered by ACF. That error would suggest ACF isn't installed or enabled on your site.

**Comment by sethvanstaden91** [comment]
Aha I see that I misunderstood the plugin. I am just trying to get the custom fields output from featured video. Will play around with ACF. Thanx
