### ISSUE TITLE
Retrieve ACF for custom post in WP REST API V2

### ISSUE THREAD

**Issue by josephclawrence** [times/acf-to-wp-api#26]
I can't seem to retrieve ACF for a custom post type of mine, using v2 of the REST API plugin. I have included 'show_in_rest' in the registration of my custom posts, and I can retrieve an individual custom post at /wp-json/wp/v2/post-type-slug/{id} but then there is no ACF endpoint it seems. The description of this plugin says you should be able to retrieve ACF for custom post types, can you offer me a pointer on what I need to do? Thank you very much

**Comment by chrishutchinson** [comment]
Hey @josephclawrence, I'm hoping that you were able to sort this given you've closed the issue.

Let me know if not!

**Comment by josephclawrence** [comment]
I was, I was being an idiot - usually the way with these things. No problem
with what you have created at all. Thanks very much!

On Mon, Sep 28, 2015 at 4:32 PM, Chris Hutchinson notifications@github.com
wrote:

> Hey @josephclawrence https://github.com/josephclawrence, I'm hoping
> that you were able to sort this given you've closed the issue.
> 
> Let me know if not!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/times/acf-to-wp-api/issues/26#issuecomment-143660575.

## 

Director
Clickshape (Pty) Ltd
www.clickshape.com
Twitter http://www.twitter.com/josephclawrence | LinkedIn
http://www.linkedin.com/in/josephclawrence | Website
http://www.clickshape.com
