### ISSUE TITLE
ACF Image size

### ISSUE THREAD

**Issue by halvardos** [times/acf-to-wp-api#27]
Hi.
First of all, thank you for creating this plugin!

At the moment, when i have a image field in acf , only the full size source is given to the json.
Should urls for all image sizes be added to the json?

Maybe with all the fields that wp-api usually gives you with an attachment?

**Comment by chrishutchinson** [comment]
Hey @Jeger,

You should be able to do this by changing your ACF configuration for image fields. See the "Return Value" setting within the field. When set to "Image Object" you'll get an object containing all the field sizes, not just the URL.

<img width="584" alt="ACF Image Return Value" src="https://cloud.githubusercontent.com/assets/1573022/10132024/19bc834c-65cc-11e5-85ce-5eb80630e0c1.png">

Cheers,
Chris

**Comment by halvardos** [comment]
Ah, i'm so sorry to waste your time.

Thank you so much for developing this plugin, and answering stupid questions :smile:
