### ISSUE TITLE
Submit to WordPress Plugin Directory

### ISSUE THREAD

**Issue by chrishutchinson** [times/acf-to-wp-api#4]
Will be doing this today

**Comment by chrishutchinson** [comment]
Submitted initial request - currently pending review from WordPress

**Comment by aendra-rininsland** [comment]
Woop woop! Now you too can have people wonder why your README is in `.txt` and not `.md`! :smile:

**Comment by aendra-rininsland** [comment]
(Speaking of which — you submitted your README as .txt, right? :wink: )

**Comment by chrishutchinson** [comment]
Woop! https://wordpress.org/plugins/acf-to-wp-api/

**Comment by aendra-rininsland** [comment]
:tada: :shipit: :boom: Congrats!

**Comment by MattieTK** [comment]
Yay :+1:
