### ISSUE TITLE
Possible to group ACF output by ACF field group

### ISSUE THREAD

**Issue by mcrider** [times/acf-to-wp-api#46]
Is it possible to group fields in a post's JSON by the ACF field group?  When I request my post's JSON through wp-api i get a flat list of fields underneath `acf`.  I need something grouped so i can determine what module to display in my front-end but also there is a practical concern of fields from different field groups with the same name overriding each other in the output.

**Comment by sheriffderek** [comment]
Can you post some example JSON for that? I often use name spaced style property names - but haven't run into this yet. It would definitely have me adjusting my practices.

`description` for "item" and `description` for "product"  --- I would rather not `product.product_description` - if possible / for readability and feels so redundant when there are 10+ fields.

**Comment by mcrider** [comment]
Actually, I just tested it out, and it seems that ACF itself won't accept the same field name in different field groups.  I.e. if you have the field 'headline' in two different field groups on the same post, whatever value you enter in the last one will be saved to that and the other headline field.  Yikes!

I guess I have to namespace the field names themselves.  I can see your point about redundancy with subgrouping them but this just adds a lot of complexity to what I want to do. What I'm trying to do is use WP as a backend to my react-based app. I want to fetch a set of data from wordpress, iterate across the custom field groups, and for each field group load up its corresponding react component.  It seems my only option is to enforce namespaces on each field name, then parse them on the frontend to determine what components I need to load.  Kinda ugly :P

**Comment by sheriffderek** [comment]
I just checked my stuff - and I guess I actually did prefix the field names the whole time. I just change their Titles in for the admin to look pretty.

**Comment by mcrider** [comment]
Thanks for helping me clear it up.  Gonna close this.
