### ISSUE TITLE
/posts, /pages, /options coming up 500

### ISSUE THREAD

**Issue by sheriffderek** [times/acf-to-wp-api#6]
/wp-json pulls up all of the routes, but /posts, /pages, /options are coming up 500 when I have this plugin installed.

Some discussion over here, might pertain: https://github.com/WP-API/WP-API/issues/475

Seems like a few days ago this started happening.

Any ideas?

**Comment by chrishutchinson** [comment]
Will take a look, are there any error messages reported in your server logs?

**Comment by chrishutchinson** [comment]
I've not been able to reproduce the issue on an entirely clean version of:
- WordPress v4.1.1
- ACF v4.4.0
- WP-API v1.1.1
- ACF to WP-API v1.1.0

I'm not ruling out this plugin though, it's very possible it's still causing the issue! Getting both some server error logs and version numbers of all the plugins you're running should help us get to the bottom of this.

**Comment by sheriffderek** [comment]
Thanks for making me retrace my steps again. Turned out that the ACF was deactivating itself for some reason. Reinstallation of 5.2 got everything back to normal. Thank you for your time.

The issue was not caused by this plugin, just some whacky mystery.

**Comment by chrishutchinson** [comment]
Excellent, glad the problem is solved, and that you're finding the plugin useful!
