### ISSUE TITLE
Is it possibile to EDIT / CREATE acf fields using this plugin?

### ISSUE THREAD

**Issue by gino8080** [times/acf-to-wp-api#7]
I'm getting mad tryng to save / edit custom metas or acf metas using the wp-rest-api

i know i can create s SINGLE meta with
POST /posts/<id>/meta

or update using
PUT /posts/<id>/meta/<mid>

but I want to update multiple at once

I know the pods plugin https://github.com/pods-framework/pods-json-api does it

please anyone caa help?

thank you!

**Comment by chrishutchinson** [comment]
This isn't able to update multiple metas at once, are you trying to avoid having to make multiple PUT/POST requests to the WP API (as that would be the current solution, looping through those you want to add / update)?

As the core WP API plugin offers the ability to update meta, I don't see much value in extending this plugin to offer that functionality, I would suggest adding the ability to update multiple metas should be added to the core plugin.

Let me know if I've missed something though!

Chris

**Comment by gino8080** [comment]
yeah thank you i would like to avoid the multiple PUT/POST requests to the WP API

as I understood this is a security decision from the WP-API team
to avoid multiple metas editing..
don'w know why? :(

for now I've solved using a simple ajax wordpress function something like:

```
add_action( 'wp_ajax_ajax_edit_multy_metas', 'edit_multy_metas' );
function edit_multy_metas(){
  $post_id =  $_REQUEST["post_id"];
  $custom_metas =  $_REQUEST["custom_metas"];

  //checking also correct nonce..

foreach ($custom_metas as $meta => $value) {
    update_post_meta( $post_id, $meta, $value);
    error_log($key ." -> ".$value) ;
  }

return get_post( $post_id);
exit;

}
```

thank you very much !
Gino

**Comment by chrishutchinson** [comment]
I'll keep an eye out for any changes to the core WP-API plugin, but I suspect they have very good reason for only allowing the editing of single metas.

I'm going to close this specific issue for now, however will bear it in mind for future enhancements.
